### ISSUE TITLE
type annotation in Typescript files shows "Type annotations can only be used in TypeScript files"

### ISSUE THREAD

**Issue by xqliu** [manateelazycat/lsp-bridge#316]
Hi,

Found one possible bug

Screenshot:

![image](https://user-images.githubusercontent.com/22554/184560695-48c42feb-9936-4268-bba5-81b7a876ed1c.png)

Using the default js-jsx-mode

The file suffix is "tsx"

Configures 

```

(setq lsp-bridge-default-mode-hooks
      '(java-mode-hook
        typescript-tsx-mode-hook
        typescript-mode-hook
        js2-mode-hook
        js-mode-hook
        rjsx-mode-hook
        org-mode-hook
        lisp-interaction-mode-hook
        sh-mode-hook
        web-mode-hook
        css-mode-hook
        emacs-lisp-mode-hook
        js-jsx-mode-hook
        )
      )

(setq lsp-bridge-single-lang-server-mode-list
      '(
        ((c-mode c++-mode) . "clangd")
        (java-mode . "jdtls")
        (python-mode . "pyright")
        (ruby-mode . "solargraph")
        ((rust-mode rustic-mode) . "rust-analyzer")
        (elixir-mode . "elixirLS")
        (go-mode . "gopls")
        (haskell-mode . "hls")
        (lua-mode . "sumneko")
        (dart-mode . "dart-analysis-server")
        (scala-mode . "metals")
        ((js2-mode js-mode rjsx-mode) . "javascript")
        ((js-jsx-mode typescript-tsx-mode) . "typescriptreact")
        ((typescript-mode) . "typescript")
        (tuareg-mode . "ocamllsp")
        (erlang-mode . "erlang-ls")
        ((latex-mode Tex-latex-mode texmode context-mode texinfo-mode bibtex-mode) . "texlab")
        ((clojure-mode clojurec-mode clojurescript-mode clojurex-mode) . "clojure-lsp")
        ((sh-mode) . "bash-language-server")
        ((css-mode) . "vscode-css-language-server")
        (elm-mode . "elm-language-server")
        )
      )
```

**Comment by manateelazycat** [comment]
Use 

` ((js-jsx-mode typescript-tsx-mode) . "typescript")` instead

**Comment by xqliu** [comment]
Hi,

Thanks for replying, it seems to have change accordingly, and the issue still exists.

Thanks :)

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/blob/d9940fd1b1a1d7513d8b1758f085cbb69fe955cf/langserver/typescript.json#L3

Change from `typescript` to `TypeScript` will fix this?

**Comment by xqliu** [comment]
The issue seems has been resolved, I will keep monitoring for 1 - 2 days to make sure it indeed has been fixed and then close this ticket.

Thanks for your suggestion and work :)

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lsp-bridge/commit/a6bf0cb67561bec3694fa84c7e5dc1ff3148ffb8 has fixed this issue.

Please create new issue if still have problem.
